### PR TITLE
feat(editor): improve panels

### PR DESCRIPTION
**Pull request by Quentin-Guillemin**

### CODE REVIEW

**Review by veigap — APPROVED** [review]

**Review by veigap — APPROVED** [review]

**Review by veigap — APPROVED** [review]

**Review by veigap — APPROVED** [review]

**Review by veigap — APPROVED** [review]

**Review by veigap — APPROVED** [review]

**Comment by veigap** [comment]
Would you mind resolving the conflicts and send the PR again ?

**Comment by veigap** [comment]
Closing PR, merging manually.

**Comment by Quentin-Guillemin** [comment]
We're not in the same time zone. Give me more time if I have to rebase next time ;)

**Comment by veigap** [comment]
No worries ! The fix was nice small change that I wanted to release :)

**Pull request closed without merging**
